services:
  ai-shark-app:
    container_name: ai-shark-streamlit
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-shark-app:latest # Explicitly name the image
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./outputs:/app/outputs
    restart: unless-stopped
